# Generated by Django 3.1.7 on 2021-04-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20210420_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='response',
            new_name='response_to',
        ),
    ]
