# Generated by Django 3.1.7 on 2021-04-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20210420_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='response_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.comment'),
        ),
    ]
