# Generated by Django 3.1.7 on 2021-05-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20210425_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumbnails'),
        ),
    ]
